### ISSUE TITLE
Greg Will and Lydia Lawson

### ISSUE THREAD

**Issue by Shell1979** [mi1971/v2#4]
I am not able to delete the follow up task

**Comment by mi1971** [comment]
Try shift-delete

Matt Ireland
0413 9999 51
Sent from my iPhone

> On 13 Aug 2018, at 4:21 pm, Shell1979 <notifications@github.com> wrote:
> 
> I am not able to delete the follow up task
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
This message may contain legally privileged, confidential and/or 
copyrighted information. If you are not the intended recipient of this 
message, please immediately notify the sender and delete the email and any 
attachments, and any copies without dissemination or use. Receipt by an 
unintended recipient does not waive legal professional privilege. Any views 
expressed in this message are those of the individual  sender, except where 
the sender specifically, and with authority, states them to be the views of 
Mortgage Choice Limited or a related company. No representation, warranty 
or guarantee is made that this email or any attachment is free from 
viruses, errors, interference or other defect. This notice should not be 
deleted or altered.
